duckdb_clickbench:
  target: default
  outputs:
    default:
      type: duckdb
      path: data/clickbench.duckdb
      schema: main
      threads: 1
      extensions:
        - parquet
        - httpfs
      settings:
        parquet_metadata_cache: true
        memory_limit: '8GB'
        preserve_insertion_order: false

    clickbench_2GB:
      type: duckdb
      path: data/clickbench.duckdb
      schema: main
      threads: 1
      extensions:
        - parquet
        - httpfs
      settings:
        parquet_metadata_cache: true
        memory_limit: '2GB'
        preserve_insertion_order: false

    clickbench_8GB:
      type: duckdb
      path: data/clickbench.duckdb
      schema: main
      threads: 1
      extensions:
        - parquet
        - httpfs
      settings:
        parquet_metadata_cache: true
        memory_limit: '8GB'
        preserve_insertion_order: false

    clickbench_24GB:
      type: duckdb
      path: data/clickbench.duckdb
      schema: main
      threads: 1
      extensions:
        - parquet
        - httpfs
      settings:
        parquet_metadata_cache: true
        memory_limit: '24GB'
        preserve_insertion_order: false

    incremental_single_thread:
      type: duckdb
      path: data/clickbench.duckdb
      schema: main
      threads: 1
      extensions:
        - parquet
        - httpfs
      settings:
        parquet_metadata_cache: true
        memory_limit: '8GB'
        preserve_insertion_order: false
        threads: 1

    incremental_multi_thread:
      type: duckdb
      path: data/clickbench.duckdb
      schema: main
      threads: 16
      extensions:
        - parquet
        - httpfs
      settings:
        parquet_metadata_cache: true
        memory_limit: '8GB'
        preserve_insertion_order: false