duckdb_clickbench:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: data/clickbench.duckdb
      schema: main
      threads: 1
      extensions:
        - parquet
        - httpfs
      settings:
        parquet_metadata_cache: true
        memory_limit: '8GB'
        preserve_insertion_order: false

